preload = ~/Pictures/Wallpapers/wp6654679.png
wallpaper = DP-7,~/Pictures/Wallpapers/wp6654679.png
wallpaper = HDMI-A-1,~/Pictures/Wallpapers/wp6654679.png
wallpaper = ,~/Pictures/Wallpapers/wp6654679.png
