export ANSIBLE_NOCOWS=1
export GOPATH=$HOME
export GO111MODULE=on

export BAT_THEME=OneHalfDark

if command -v nvim &>/dev/null; then
  export EDITOR=$(which nvim)
else
  export EDITOR=$(which vim)
fi
# TODO Do I need this?
export SVN_EDITOR=$EDITOR

eval "$(rbenv init -)"
export PATH=$HOME/.rbenv/bin:$PATH

export PLAN9=$HOME/src/9fans/plan9port
# TODO Clean this up
# PATH=$HOME/bin:/usr/local/sbin:/usr/local/bin:$PATH:$HOME/.cargo/bin:$PLAN9/bin export PATH
export PATH=$HOME/bin:/opt/wasi-sdk-12.0/bin:/usr/local/sbin:/usr/local/bin:$HOME/.cargo/bin:$PATH

[[ -f ~/.zshenv.local ]] && source ~/.zshenv.local

if [ -e /home/andrew/.nix-profile/etc/profile.d/nix.sh ]; then . /home/andrew/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
