# Generated by nixos-generate-config on first VM install.
# Replace this file with: sudo nixos-generate-config --show-hardware-config
{ modulesPath, ... }:
{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];
  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "virtio_pci"
    "sr_mod"
    "virtio_blk"
  ];
  fileSystems."/" = {
    device = "/dev/vda1";
    fsType = "ext4";
  };
  fileSystems."/boot" = {
    device = "/dev/vda2";
    fsType = "vfat";
  };
  swapDevices = [ ];
  nixpkgs.hostPlatform = "x86_64-linux";
}
